export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#FEFDF8] pb-24 text-[#2C3E50]">
      <div className="mx-auto flex max-w-4xl flex-col gap-8 px-6 pt-12 sm:px-12">
        <header className="rounded-3xl border border-white/80 bg-white/95 p-10 shadow-[var(--shadow-lg)]" data-animate="fade-up">
          <h1 className="text-3xl font-semibold text-[#0D7377] sm:text-[2.5rem]">Terms of Use</h1>
          <p className="mt-4 text-sm text-[#2C3E50]/70 sm:text-base">
            These terms govern use of the Islamic Library website and related services. By accessing the site you agree to the responsibilities and permitted use described below.
          </p>
          <p className="mt-2 text-xs text-[#2C3E50]/50">Last updated: 2025-10-20</p>
        </header>

        <section className="rounded-3xl border border-white/70 bg-white p-8 shadow-[var(--shadow-md)]" data-animate="fade-up" data-delay="1">
          <h2 className="text-xl font-semibold text-[#0D7377]">1. Acceptable use</h2>
          <ul className="mt-3 space-y-2 text-sm text-[#2C3E50]/70">
            <li>Resources are provided for personal learning and non-commercial distribution. Do not resell or misrepresent content.</li>
            <li>Respect copyright and attribution requirements from original publishers.</li>
            <li>Refrain from malicious activity, including attempting to break rate limits or upload harmful material.</li>
          </ul>
        </section>

        <section className="rounded-3xl border border-white/70 bg-white p-8 shadow-[var(--shadow-md)]" data-animate="fade-up" data-delay="2">
          <h2 className="text-xl font-semibold text-[#0D7377]">2. Content accuracy</h2>
          <p className="mt-3 text-sm text-[#2C3E50]/70">
            We strive to host authentic and verified Islamic resources. However, final responsibility for verifying textual authenticity rests with the user. Report any issues to support@islamiclibrary.org.
          </p>
        </section>

        <section className="rounded-3xl border border-white/70 bg-white p-8 shadow-[var(--shadow-md)]" data-animate="fade-up" data-delay="3">
          <h2 className="text-xl font-semibold text-[#0D7377]">3. AI assistant</h2>
          <p className="mt-3 text-sm text-[#2C3E50]/70">
            Responses generated by the AI assistant should be treated as guidance only. Always consult qualified scholars for religious rulings. We log limited metadata to improve the assistant while respecting user privacy.
          </p>
        </section>

        <section className="rounded-3xl border border-white/70 bg-white p-8 shadow-[var(--shadow-md)]" data-animate="fade-up" data-delay="4">
          <h2 className="text-xl font-semibold text-[#0D7377]">4. Changes</h2>
          <p className="mt-3 text-sm text-[#2C3E50]/70">
            Terms may be updated periodically. Continued use of the site after changes signifies acceptance of the revised terms.
          </p>
        </section>

        <section className="rounded-3xl border border-white/70 bg-white p-8 shadow-[var(--shadow-md)]" data-animate="fade-up" data-delay="5">
          <h2 className="text-xl font-semibold text-[#0D7377]">5. Contact</h2>
          <p className="mt-3 text-sm text-[#2C3E50]/70">
            Questions or concerns? Email <a className="text-[#0D7377] underline" href="mailto:hello@islamiclibrary.org">hello@islamiclibrary.org</a>.
          </p>
        </section>
      </div>
    </main>
  );
}
